version: '3.8'
 
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
 
  lms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms_app
    ports:
      - "1111:1111"
    depends_on:
      - mysql
    environment:
      SPRING_APPLICATION_NAME: lms
      SERVER_PORT: 1111
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/learning_plan_service
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    restart: always
 
volumes:
  mysql_data: