version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: plan-db
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plandb
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learning_plan_app
    ports:
      - "1111:1111"
    depends_on:
      - mysql
    environment:
      SPRING_APPLICATION_NAME: learning-plan-service
      SERVER_PORT: 1111
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/plandb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect

volumes:
  mysql_data:
